### ISSUE TITLE
Dead url links

### ISSUE THREAD

**Issue by zawkindev** [floss-uz/awesome#5]
There are bunch of dead links in the README.md file. 
I have found these ones: "bulut, cyonix, havo, korrektor, korrektor rust lib, kusari, osmon, xinux"

**Comment by orzklv** [comment]
Please, keep reporting further dead links and I'll fix it on the fly. Thanks for your contribution!

**Comment by orzklv** [comment]
fixed: https://github.com/floss-uz/awesome/commit/883d5e27239f7b4f772ffef149e40a1ef3ebb240

**Comment by zawkindev** [comment]
Thanks for doing so much for your country. I appreciate it.
